
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FIELD NEWLINE TABline : fields\n              | fields NEWLINEfields : field\n                | field TAB fieldsfield : FIELD'
    
_lr_action_items = {'FIELD':([0,6,],[4,4,]),'$end':([1,2,3,4,5,7,],[0,-1,-3,-5,-2,-4,]),'NEWLINE':([2,3,4,7,],[5,-3,-5,-4,]),'TAB':([3,4,],[6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'fields':([0,6,],[2,7,]),'field':([0,6,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> fields','line',1,'p_statement_line','tsv_yacc.py',54),
  ('line -> fields NEWLINE','line',2,'p_statement_line','tsv_yacc.py',55),
  ('fields -> field','fields',1,'p_statement_fields','tsv_yacc.py',61),
  ('fields -> field TAB fields','fields',3,'p_statement_fields','tsv_yacc.py',62),
  ('field -> FIELD','field',1,'p_statement_field','tsv_yacc.py',70),
]
