default : helloworld helloworld2

helloworld :
	gcc -Wall -g helloworld.c -o helloworld `pkg-config gtk+-2.0 --cflags --libs`

helloworld2 :
	gcc -Wall -g helloworld2.c -o helloworld2 `pkg-config gtk+-2.0 --cflags --libs`
