OBJS = helloworld helloworld2 eventbox frame

CFLAGS = -Wall -g `pkg-config gtk+-2.0 --cflags --libs`

default : all

all : ${OBJS}

# helloworld :
# 	gcc -Wall -g helloworld.c -o helloworld `pkg-config gtk+-2.0 --cflags --libs`

# helloworld2 :
# 	gcc -Wall -g helloworld2.c -o helloworld2 `pkg-config gtk+-2.0 --cflags --libs`

# eventbox :
# 	gcc -Wall -g eventbox.c -o eventbox `pkg-config gtk+-2.0 --cflags --libs`
