.PHONY: install all

# https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#pip-installation
# Mac OS X, CPU only, Python 3.4 or 3.5:
TF_BINARY_URL := https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0-py3-none-any.whl

all:

install:
	./vexec.sh pip3 install $(TF_BINARY_URL)
