---
- hosts: all
  vars:
    helloworld: Hell, world!
    # Hide this for production!
    encrypt_key: secret_key
    decrypted_message: "{{ 'gAAAAABYy4KB8lRgVJXCTHQORp5U1cgKWk2DnhQvMRohee77-JpzKRSPQSxwn_AJe5Ts7ECgWq6O08JA0cHMBhxzLN1eSLcwRg==' | decrypt(encrypt_key) }}"

  roles:
    - { role: role1, debugmsg: "def" }
    - role: role1
      debugmsg: "eeeeeeee"

  tasks:
    - name: Print hello world
      debug: msg="{{ helloworld }}"

    - name: Print hello world with var option
      debug: var=helloworld

    - name: Print ansible_hostname
      debug: var=ansible_hostname

    - name: Try timetest.py
      timetest.py:

    - name: Try alwaysfail.py
      alwaysfail.py: arg1="{{ helloworld }}"
      ignore_errors: true

    - name: Install libselinux
      yum: name=libselinux-python state=present
      become: yes
      when: ansible_hostname == "vagr-centos66"

    - name: Disable SELinux
      selinux: state=disabled
      become: yes
      when: ansible_hostname == "vagr-centos66"

    - name: encryption_test
      debug:
        msg: "{{ decrypted_message }}"
