---
- hosts: all
  vars:
    helloworld: Hell, world!
    lastone: "{{ 'hogehoge' | lastone }}"
    idx: "{{ 'hoehoe' | idx(3) }}"
    # Hide this for production!
    encrypt_key: secret_key
    decrypted_message: "{{ 'gAAAAABYy4KB8lRgVJXCTHQORp5U1cgKWk2DnhQvMRohee77-JpzKRSPQSxwn_AJe5Ts7ECgWq6O08JA0cHMBhxzLN1eSLcwRg==' | decrypt(encrypt_key) }}"

  tasks:
    - name: copy myhttp
      copy:
        src: ./myhttp.js
        dest: /tmp/myhttp.js

    - name: pm2 started
      pm2:
        script: /tmp/myhttp.js
        state: started
        name: "app0"

    - name: pm2 restarted
      pm2:
        state: restarted
        name: "app0"

    - name: pm2 stopped
      pm2:
        state: stopped
        name: "app0"

    - name: pm2 deleted
      pm2:
        config: pm2.json
        state: deleted
        name: "app1"

    - name: pm2 no executable
      pm2:
        config: pm2.json
        state: started
        name: "app0"
        executable: "__NONEXIST"
      failed_when: false
