---
- hosts: all
  vars:
    helloworld: Hell, world!
    lastone: "{{ 'hogehoge' | lastone }}"
    idx: "{{ 'hoehoe' | idx(3) }}"
    # Hide this for production!
    encrypt_key: secret_key
    decrypted_message: "{{ 'gAAAAABYy4KB8lRgVJXCTHQORp5U1cgKWk2DnhQvMRohee77-JpzKRSPQSxwn_AJe5Ts7ECgWq6O08JA0cHMBhxzLN1eSLcwRg==' | decrypt(encrypt_key) }}"

  tasks:
    - name: pm2 start
      pm2:
        config: pm2.json
        state: started
        name: "app0"

    - name: pm2 no executable
      pm2:
        config: pm2.json
        state: started
        name: "app0"
        executable: "__NONEXIST"
