# Generated by Django 2.1.4 on 2018-12-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_timeofsleep_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afield', models.CharField(max_length=50)),
                ('note', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
