# Generated by Django 2.1.4 on 2018-12-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_amodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeOfSleep',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
