# Generated by Django 2.1.4 on 2018-12-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181206_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CModel',
        ),
    ]
