# Generated by Django 2.1.4 on 2018-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_fmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtmExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afield', models.CharField(max_length=50)),
                ('fmodel', models.ManyToManyField(to='app.FModel')),
            ],
        ),
    ]
