name: GitHub Push Branch

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch more commits
        run: |
          git fetch --depth 100 origin master
          git fetch --depth 100 origin gh-pages || true

      - name: Add Git settings
        run: |
          git config --local user.email "10sr@example.com"
          git config --local user.name "${{ github.actor }}"

      - name: Checkout branch
        run: git switch -c gh-pages origin/gh-pages || git switch -c gh-pages origin/master

      - name: Merge master
        run: git merge --no-ff origin/master

      - name: Create file
        run: bash .github/workflows/github-push-branch.sh

      - name: Commit files
        run: |
          git add .
          git commit -m "Auto commit via GitHub Actions"
          git push origin gh-pages
